parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python35-windows-min:
        python.version: '35-min'
      Python35-windows:
        python.version: '35'

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - script: conda env create --quiet --file ci/requirements-py$(python.version).yml
    displayName: Create Anaconda environment
  - script: |
      source activate test_env
      pip install pytest-azurepipelines
      pip install -e .
    displayName: 'pip dependencies'
  - script: |
      source activate test_env
      conda list
    displayName: 'List installed dependencies'
  - script: |
      source activate test_env
      pytest pvlib --remote-data --junitxml=junit/test-results.xml --cov --cov-report=xml --cov-report=html
    env:
      NREL_API_KEY: $(nrelApiKey)
    displayName: 'pytest'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Linux $(python.version)'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
    condition: eq(variables['coverage'], true)
  - script: |
      bash <(curl https://codecov.io/bash) -t $CODECOV_TOKEN -f coverage.xml -F adder -F subtractor -F conda
    env:
      CODECOV_TOKEN: $(codecov_token)
    displayName: 'codecov'
    condition: eq(variables['coverage'], true)
